### ISSUE TITLE
Must provide RUSTLER_NIF_VERSION or OTP 23 (and earlier) will fail

### ISSUE THREAD

**Issue by mischov** [philss/rustler-precompiled-action#1]
I have recently been implementing NIF precompilation for Meeseeks (thank you for all your work on this @philss) and I hit an awful bug where I had precompilation working fine in `meeseeks_html5ever` but my OTP 23 test in Meeseeks that used the precompiled nif segfaulted.

```
==> rustler_precompiled
Compiling 4 files (.ex)
Generated rustler_precompiled app
==> meeseeks_html5ever
Compiling 2 files (.ex)

[debug] Downloading NIF from https://github.com/mischov/meeseeks_html5ever/releases/download/v0.14.2/libmeeseeks_html5ever_nif-v0.14.2-nif-2.15-x86_64-unknown-linux-gnu.so.tar.gz

[debug] NIF cached at /home/runner/.cache/rustler_precompiled/precompiled_nifs/libmeeseeks_html5ever_nif-v0.14.2-nif-2.15-x86_64-unknown-linux-gnu.so.tar.gz and extracted to /home/runner/work/meeseeks/meeseeks/_build/test/lib/meeseeks_html5ever/priv/native/libmeeseeks_html5ever_nif-v0.14.2-nif-2.15-x86_64-unknown-linux-gnu.so
/home/runner/work/_temp/444ec869-fec7-4358-9f2e-fb265b93b51d.sh: line 4:  1983 Segmentation fault      (core dumped) mix deps.compile
[error]Process completed with exit code 139.
```

No doubt you're immediately flashing back to https://github.com/philss/rustler_precompiled/issues/23, and that's indeed where the segfault led me.

Unfortunately for me I had already correctly set `Cross.toml` as appropriate, and the compilation target wasn't using cross anyway.

Anyway, long and frustrating story short, I went searching for `RUSTLER_NIF_VERSION` in `rustler-precompiled-action` and didn't find it, so I added it to my release workflow and the problem was solved.

```
env:
  RUSTLER_NIF_VERSION: ${{ matrix.nif }}
```

The example project does not contain that, nor does any of the other usages in release workflows (in `html5ever` or `explorer`, for example) so it's quite possible that usage on OTP 23 or lower for all of those projects is broken.

I don't know if `env` should be set in release workflows like I've done, or if `rustler-precompiled-action` should use `nif-version` to set that itself (which is what I was assuming was happening before I checked).

I also don't know how this could have been tested for, since it requires that the precompiled NIFs be used in a different project to surface.

**Comment by philss** [comment]
Oh my, this is embarrassing :flushed: 
Thanks for finding out!
 
> I don't know if env should be set in release workflows like I've done, or if rustler-precompiled-action should use nif-version to set that itself (which is what I was assuming was happening before I checked)

I think we should add that to the Action.

> I also don't know how this could have been tested for, since it requires that the precompiled NIFs be used in a different project to surface.

Ideally we could have a "smoke test" of the application booting on each different version of OTP. But I think this shouldn't be scope of this project. We could, however, document that. WDYT?

**Comment by mischov** [comment]
Between Apple silicon compatibility issues and openssl issues it's actually surprisingly difficult to use OTP 23 for development, so it's quite possible people just haven't been encountering the issue. I only found it due to automated compatibility testing.

I agree that the most natural place to set the env would be the action because we are already providing the `nif-version` to it.

One possibility for smoke testing would be to somehow automate the usage of `rustler_precompilation_example` as a dependency for something over the versions `rustler_precompilation_example` is good for, which would at least help assure that people copying the example project should get something that works.

**Comment by philss** [comment]
> Between Apple silicon compatibility issues and openssl issues it's actually surprisingly difficult to use OTP 23 for development, so it's quite possible people just haven't been encountering the issue. I only found it due to automated compatibility testing.

I see. Maybe it's a good sign that people are trying newer versions of OTP :smile: 

 > I agree that the most natural place to set the env would be the action because we are already providing the nif-version to it.

I opened this PR: https://github.com/philss/rustler-precompiled-action/pull/2
But I didn't test it yet. Going to do that in a few minutes.

> One possibility for smoke testing would be to somehow automate the usage of rustler_precompilation_example as a dependency for something over the versions rustler_precompilation_example is good for, which would at least help assure that people copying the example project should get something that works.

I'm not sure if I get it :thinking: 
My only concern is that we may need the file SHA256 written to the disk in order to make it load in the smoke test.
I think it's feasible, but it may be complicated to get it working.

**Comment by mischov** [comment]
For sure it would be complicated to figure out how to get some kind of automated testing working, and it's probably not worth the time at the moment. 

If similar issues keep popping up maybe it would be worth investigating further, but things seems like they've been pretty solid.

**Comment by philss** [comment]
@mischov version `1.0.1` was released with a fix. Please use that version in your workflow.

I'm closing this for now. Thanks again!
