### ISSUE TITLE
Option to install cross from source

### ISSUE THREAD

**Issue by satoren** [philss/rustler-precompiled-action#6]
I am running into a problem with cross v0.2.5.
But with the latest in the repository there is no problem. https://github.com/cross-rs/cross/issues/1302#issuecomment-1721730825
It would be nice if there was an option to install from source as the next release of cross is not readily available.

https://github.com/cross-rs/cross#installation

**Comment by philss** [comment]
We could accept the value `"from-source"` in the `"cross-version"` input. This way we could switch between installing from the binary and from the repository. WDYT?

**Comment by satoren** [comment]
Sounds good!

**Comment by satoren** [comment]
Thank you!
